### ISSUE TITLE
Deleting a URL does not work

### ISSUE THREAD

**Issue by phindmarsh** [jethrocarr/ghoch#1]
I needed to delete a URL but it didn't work. Now I have a URL I can't delete. Deleting a URL should be  part of MVP. Please fix.

**Comment by AlexQuinlivan** [comment]
+1 me too. Thanks

**Comment by jethrocarr** [comment]
Hello $valued_customer,

I see you've found our value-added data protection and integrity assurance feature, we're glad you've enjoyed it as much as we enjoyed writing it!

As a hip young startup, we welcome all kinds of feedback, said feedback can be provided via our kickstarter campaign where you can vote for the features you want with a point system where you indicate the features you desire by buying various number of cheap tshirts and sticks that we may or may not ship.

regards,
Jethro

Vice President of Vice
AgileCorp

**Comment by jethrocarr** [comment]
Because I care so much, fixed in https://github.com/jethrocarr/ghoch/commit/daec396e121b709bcb52f9b996e4772637a3c156 :-P
